import './global.css';

export const metadata = {
  title: 'Welcome to healthcheck',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className='min-h-screen grid place-content-center'>{children}</body>
    </html>
  );
}
