name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@latest
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Set up PNPM
        uses: pnpm/action-setup@latest
        with:
          version: latest

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="build"

      - name: Install Node.js
        uses: actions/setup-node@latest
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set NX base and head SHAs
        uses: nrwl/nx-set-shas@v4

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World

      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      - name: Lint affected projects
        run: pnpm exec nx affected -t lint

      - name: Test affected projects
        run: pnpm exec nx affected -t test

      - name: Build affected projects
        run: pnpm exec nx affected -t build

      # Placeholder for Deploy step - uncomment and adjust when deployment is configured
      # - name: Deploy affected projects (if applicable)
      #   run: |
      #     echo "Deployment step placeholder"
      #     # Add deployment commands here
