name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-doc:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    # Define an output to signal if an artifact was actually prepared for upload
    outputs:
      artifact-uploaded: ${{ steps.check-build.outputs.builded }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - name: Set up PNPM
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      # Add this step to set the base and head SHAs for nx affected
      - name: Set Base and Head SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Build website
        run: npx nx affected:build

      # New step: Check if build output exists and set an output variable
      - name: Check build output and set build flag
        id: check-build
        run: |
          if [ -d "dist/apps/docs" ]; then
            echo "Build output found for docs."
            echo "builded=true" >> $GITHUB_OUTPUT
          else
            echo "No build output found for docs. Skipping upload and deploy."
            echo "builded=false" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        # Only run if the check-build step set builded=true
        if: steps.check-build.outputs.builded == 'true'
        with:
          path: dist/apps/docs

  deploy-doc:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-doc

    # Only deploy if artifact has been built
    if: needs.build-doc.outputs.artifact-uploaded == 'true'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
